import "dotenv/config"; // must be the very first line in this file

import { PrismaNeon } from "@prisma/adapter-neon";
import { PrismaClient } from "../src/generated/prisma/client";

const adapter = new PrismaNeon({
  connectionString: process.env.DATABASE_URL,
});

const prisma = new PrismaClient({
  adapter,
});

const userId = "df43ddcc-1c83-4d14-9542-5c518b7059c3";

const movies = [
  {
    title: "The Matrix",
    overview:
      "A hacker discovers that reality is a simulated world controlled by machines.",
    releaseYear: 1999,
    genres: ["Action", "Sci-Fi"],
    runtime: 136,
    posterUrl: "https://example.com/posters/the-matrix.jpg",
    createdBy: userId,
  },
  {
    title: "Inception",
    overview: "A skilled thief enters dreams to steal and plant ideas.",
    releaseYear: 2010,
    genres: ["Action", "Sci-Fi", "Thriller"],
    runtime: 148,
    posterUrl: "https://example.com/posters/inception.jpg",
    createdBy: userId,
  },
  {
    title: "Interstellar",
    overview: "Explorers travel through a wormhole to save humanity.",
    releaseYear: 2014,
    genres: ["Adventure", "Drama", "Sci-Fi"],
    runtime: 169,
    posterUrl: "https://example.com/posters/interstellar.jpg",
    createdBy: userId,
  },
  {
    title: "The Dark Knight",
    overview: "Batman faces the Joker in Gotham City's greatest test.",
    releaseYear: 2008,
    genres: ["Action", "Crime", "Drama"],
    runtime: 152,
    posterUrl: "https://example.com/posters/the-dark-knight.jpg",
    createdBy: userId,
  },
  {
    title: "The Shawshank Redemption",
    overview: "Two prisoners form a lifelong friendship behind bars.",
    releaseYear: 1994,
    genres: ["Drama"],
    runtime: 142,
    posterUrl: "https://example.com/posters/shawshank-redemption.jpg",
    createdBy: userId,
  },
  {
    title: "The Godfather",
    overview: "A mafia patriarch prepares his reluctant son to take over.",
    releaseYear: 1972,
    genres: ["Crime", "Drama"],
    runtime: 175,
    posterUrl: "https://example.com/posters/the-godfather.jpg",
    createdBy: userId,
  },
  {
    title: "Pulp Fiction",
    overview: "Multiple crime stories intertwine in Los Angeles.",
    releaseYear: 1994,
    genres: ["Crime", "Drama"],
    runtime: 154,
    posterUrl: "https://example.com/posters/pulp-fiction.jpg",
    createdBy: userId,
  },
  {
    title: "Fight Club",
    overview: "An office worker starts an underground fight club.",
    releaseYear: 1999,
    genres: ["Drama"],
    runtime: 139,
    posterUrl: "https://example.com/posters/fight-club.jpg",
    createdBy: userId,
  },
  {
    title: "Forrest Gump",
    overview: "A kind-hearted man witnesses major events in American history.",
    releaseYear: 1994,
    genres: ["Drama", "Romance"],
    runtime: 142,
    posterUrl: "https://example.com/posters/forrest-gump.jpg",
    createdBy: userId,
  },
  {
    title: "Goodfellas",
    overview: "The rise and fall of a mob associate.",
    releaseYear: 1990,
    genres: ["Biography", "Crime", "Drama"],
    runtime: 146,
    posterUrl: "https://example.com/posters/goodfellas.jpg",
    createdBy: userId,
  },
  {
    title: "Gladiator",
    overview: "A betrayed Roman general seeks revenge.",
    releaseYear: 2000,
    genres: ["Action", "Adventure", "Drama"],
    runtime: 155,
    posterUrl: "https://example.com/posters/gladiator.jpg",
    createdBy: userId,
  },
  {
    title: "The Lord of the Rings: The Fellowship of the Ring",
    overview: "A hobbit begins a quest to destroy a powerful ring.",
    releaseYear: 2001,
    genres: ["Adventure", "Fantasy"],
    runtime: 178,
    posterUrl: "https://example.com/posters/fellowship.jpg",
    createdBy: userId,
  },
  {
    title: "The Lord of the Rings: The Two Towers",
    overview: "The fellowship continues its battle against evil.",
    releaseYear: 2002,
    genres: ["Adventure", "Fantasy"],
    runtime: 179,
    posterUrl: "https://example.com/posters/two-towers.jpg",
    createdBy: userId,
  },
  {
    title: "The Lord of the Rings: The Return of the King",
    overview: "The final battle for Middle-earth begins.",
    releaseYear: 2003,
    genres: ["Adventure", "Fantasy"],
    runtime: 201,
    posterUrl: "https://example.com/posters/return-king.jpg",
    createdBy: userId,
  },
  {
    title: "The Prestige",
    overview: "Two rival magicians compete with dangerous consequences.",
    releaseYear: 2006,
    genres: ["Drama", "Mystery", "Thriller"],
    runtime: 130,
    posterUrl: "https://example.com/posters/prestige.jpg",
    createdBy: userId,
  },
  {
    title: "Memento",
    overview: "A man with memory loss hunts his wife's killer.",
    releaseYear: 2000,
    genres: ["Mystery", "Thriller"],
    runtime: 113,
    posterUrl: "https://example.com/posters/memento.jpg",
    createdBy: userId,
  },
  {
    title: "The Green Mile",
    overview: "A prison guard witnesses extraordinary miracles.",
    releaseYear: 1999,
    genres: ["Crime", "Drama", "Fantasy"],
    runtime: 189,
    posterUrl: "https://example.com/posters/green-mile.jpg",
    createdBy: userId,
  },
  {
    title: "Saving Private Ryan",
    overview: "Soldiers risk everything to rescue one man.",
    releaseYear: 1998,
    genres: ["Drama", "War"],
    runtime: 169,
    posterUrl: "https://example.com/posters/saving-private-ryan.jpg",
    createdBy: userId,
  },
  {
    title: "Se7en",
    overview: "Detectives hunt a serial killer using deadly sins.",
    releaseYear: 1995,
    genres: ["Crime", "Mystery", "Thriller"],
    runtime: 127,
    posterUrl: "https://example.com/posters/se7en.jpg",
    createdBy: userId,
  },
  {
    title: "Whiplash",
    overview: "A young drummer struggles under a demanding mentor.",
    releaseYear: 2014,
    genres: ["Drama", "Music"],
    runtime: 106,
    posterUrl: "https://example.com/posters/whiplash.jpg",
    createdBy: userId,
  },
  {
    title: "Parasite",
    overview: "A poor family infiltrates a wealthy household.",
    releaseYear: 2019,
    genres: ["Drama", "Thriller"],
    runtime: 132,
    posterUrl: "https://example.com/posters/parasite.jpg",
    createdBy: userId,
  },
  {
    title: "Joker",
    overview: "A failed comedian descends into madness.",
    releaseYear: 2019,
    genres: ["Crime", "Drama", "Thriller"],
    runtime: 122,
    posterUrl: "https://example.com/posters/joker.jpg",
    createdBy: userId,
  },
  {
    title: "Avengers: Endgame",
    overview: "The Avengers make one final stand against Thanos.",
    releaseYear: 2019,
    genres: ["Action", "Adventure", "Sci-Fi"],
    runtime: 181,
    posterUrl: "https://example.com/posters/endgame.jpg",
    createdBy: userId,
  },
  {
    title: "Avengers: Infinity War",
    overview: "The Avengers face the powerful Thanos.",
    releaseYear: 2018,
    genres: ["Action", "Adventure", "Sci-Fi"],
    runtime: 149,
    posterUrl: "https://example.com/posters/infinity-war.jpg",
    createdBy: userId,
  },
  {
    title: "Spider-Man: No Way Home",
    overview: "Peter Parker faces villains from other universes.",
    releaseYear: 2021,
    genres: ["Action", "Adventure", "Sci-Fi"],
    runtime: 148,
    posterUrl: "https://example.com/posters/no-way-home.jpg",
    createdBy: userId,
  },
  {
    title: "Top Gun: Maverick",
    overview: "A veteran pilot trains the next generation.",
    releaseYear: 2022,
    genres: ["Action", "Drama"],
    runtime: 130,
    posterUrl: "https://example.com/posters/top-gun-maverick.jpg",
    createdBy: userId,
  },
  {
    title: "Dune",
    overview: "A young nobleman embraces his destiny on Arrakis.",
    releaseYear: 2021,
    genres: ["Adventure", "Drama", "Sci-Fi"],
    runtime: 155,
    posterUrl: "https://example.com/posters/dune.jpg",
    createdBy: userId,
  },
  {
    title: "Dune: Part Two",
    overview: "Paul Atreides leads a rebellion across Arrakis.",
    releaseYear: 2024,
    genres: ["Adventure", "Drama", "Sci-Fi"],
    runtime: 166,
    posterUrl: "https://example.com/posters/dune-part-two.jpg",
    createdBy: userId,
  },
  {
    title: "Oppenheimer",
    overview: "The story of the scientist behind the atomic bomb.",
    releaseYear: 2023,
    genres: ["Biography", "Drama", "History"],
    runtime: 180,
    posterUrl: "https://example.com/posters/oppenheimer.jpg",
    createdBy: userId,
  },
  {
    title: "Barbie",
    overview: "Barbie questions her perfect world.",
    releaseYear: 2023,
    genres: ["Adventure", "Comedy", "Fantasy"],
    runtime: 114,
    posterUrl: "https://example.com/posters/barbie.jpg",
    createdBy: userId,
  },
  {
    title: "The Batman",
    overview: "Batman uncovers corruption while hunting the Riddler.",
    releaseYear: 2022,
    genres: ["Action", "Crime", "Drama"],
    runtime: 176,
    posterUrl: "https://example.com/posters/the-batman.jpg",
    createdBy: userId,
  },
  {
    title: "The Wolf of Wall Street",
    overview: "A stockbroker rises and falls through greed.",
    releaseYear: 2013,
    genres: ["Biography", "Comedy", "Crime"],
    runtime: 180,
    posterUrl: "https://example.com/posters/wolf-wall-street.jpg",
    createdBy: userId,
  },
  {
    title: "La La Land",
    overview: "Two artists pursue love and ambition in Los Angeles.",
    releaseYear: 2016,
    genres: ["Drama", "Music", "Romance"],
    runtime: 128,
    posterUrl: "https://example.com/posters/la-la-land.jpg",
    createdBy: userId,
  },
  {
    title: "The Social Network",
    overview: "The rise of Facebook and its founders.",
    releaseYear: 2010,
    genres: ["Biography", "Drama"],
    runtime: 120,
    posterUrl: "https://example.com/posters/social-network.jpg",
    createdBy: userId,
  },
  {
    title: "The Silence of the Lambs",
    overview: "An FBI trainee seeks help from a brilliant killer.",
    releaseYear: 1991,
    genres: ["Crime", "Drama", "Thriller"],
    runtime: 118,
    posterUrl: "https://example.com/posters/silence-lambs.jpg",
    createdBy: userId,
  },
  {
    title: "The Departed",
    overview: "An undercover cop and a mole race to uncover each other.",
    releaseYear: 2006,
    genres: ["Crime", "Drama", "Thriller"],
    runtime: 151,
    posterUrl: "https://example.com/posters/departed.jpg",
    createdBy: userId,
  },
  {
    title: "Shutter Island",
    overview: "A U.S. Marshal investigates a mysterious disappearance.",
    releaseYear: 2010,
    genres: ["Mystery", "Thriller"],
    runtime: 138,
    posterUrl: "https://example.com/posters/shutter-island.jpg",
    createdBy: userId,
  },
  {
    title: "The Lion King",
    overview: "A lion prince returns to reclaim his kingdom.",
    releaseYear: 1994,
    genres: ["Animation", "Adventure", "Drama"],
    runtime: 88,
    posterUrl: "https://example.com/posters/lion-king.jpg",
    createdBy: userId,
  },
  {
    title: "Toy Story",
    overview: "Toys come to life when humans are away.",
    releaseYear: 1995,
    genres: ["Animation", "Adventure", "Comedy"],
    runtime: 81,
    posterUrl: "https://example.com/posters/toy-story.jpg",
    createdBy: userId,
  },
  {
    title: "Finding Nemo",
    overview: "A clownfish searches the ocean for his missing son.",
    releaseYear: 2003,
    genres: ["Animation", "Adventure", "Comedy"],
    runtime: 100,
    posterUrl: "https://example.com/posters/finding-nemo.jpg",
    createdBy: userId,
  },
  {
    title: "Coco",
    overview: "A young musician journeys into the Land of the Dead.",
    releaseYear: 2017,
    genres: ["Animation", "Adventure", "Family"],
    runtime: 105,
    posterUrl: "https://example.com/posters/coco.jpg",
    createdBy: userId,
  },
  {
    title: "Inside Out",
    overview: "A girl's emotions guide her through major life changes.",
    releaseYear: 2015,
    genres: ["Animation", "Adventure", "Comedy"],
    runtime: 95,
    posterUrl: "https://example.com/posters/inside-out.jpg",
    createdBy: userId,
  },
  {
    title: "Mad Max: Fury Road",
    overview: "Survivors flee across a post-apocalyptic wasteland.",
    releaseYear: 2015,
    genres: ["Action", "Adventure"],
    runtime: 120,
    posterUrl: "https://example.com/posters/mad-max-fury-road.jpg",
    createdBy: userId,
  },
  {
    title: "John Wick",
    overview: "A retired assassin seeks revenge.",
    releaseYear: 2014,
    genres: ["Action", "Crime", "Thriller"],
    runtime: 101,
    posterUrl: "https://example.com/posters/john-wick.jpg",
    createdBy: userId,
  },
  {
    title: "John Wick: Chapter 4",
    overview: "John Wick battles the High Table across the globe.",
    releaseYear: 2023,
    genres: ["Action", "Crime", "Thriller"],
    runtime: 169,
    posterUrl: "https://example.com/posters/john-wick-4.jpg",
    createdBy: userId,
  },
  {
    title: "No Country for Old Men",
    overview: "A hunter finds money that sparks deadly pursuit.",
    releaseYear: 2007,
    genres: ["Crime", "Drama", "Thriller"],
    runtime: 122,
    posterUrl: "https://example.com/posters/no-country-for-old-men.jpg",
    createdBy: userId,
  },
  {
    title: "Blade Runner 2049",
    overview: "A young blade runner uncovers a buried secret.",
    releaseYear: 2017,
    genres: ["Drama", "Mystery", "Sci-Fi"],
    runtime: 164,
    posterUrl: "https://example.com/posters/blade-runner-2049.jpg",
    createdBy: userId,
  },
  {
    title: "The Revenant",
    overview: "A frontiersman fights for survival after betrayal.",
    releaseYear: 2015,
    genres: ["Adventure", "Drama"],
    runtime: 156,
    posterUrl: "https://example.com/posters/revenant.jpg",
    createdBy: userId,
  },
  {
    title: "Everything Everywhere All at Once",
    overview: "A woman must save the multiverse while fixing her family.",
    releaseYear: 2022,
    genres: ["Action", "Adventure", "Comedy"],
    runtime: 139,
    posterUrl: "https://example.com/posters/everything-everywhere.jpg",
    createdBy: userId,
  },
  {
    title: "Arrival",
    overview: "A linguist communicates with mysterious alien visitors.",
    releaseYear: 2016,
    genres: ["Drama", "Mystery", "Sci-Fi"],
    runtime: 116,
    posterUrl: "https://example.com/posters/arrival.jpg",
    createdBy: userId,
  },
];

const main = async () => {
  console.log("Seeding movies...");

  for (const movie of movies) {
    await prisma.movie.create({
      data: movie,
    });
    console.log(`Created movie: ${movie.title}`);
  }

  console.log("Seeding completed!");
};

main()
  .catch((err) => {
    console.error(err);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
